# SPDX-License-Identifier: GPL-2.0 OR BSD-3-Clause

imx_hdp_common-y := API_Audio.o API_AVI.o API_AFE.o API_General.o \
	     API_HDCP.o API_HDMITX.o API_HDMI_Audio.o \
	     API_Infoframe.o API_DPTX.o util.o
obj-$(CONFIG_MX8_HDP) += imx_hdp_common.o
